package Catan;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
/**
 *
 * @author  Steven De Toni
 * 
 *  April 2008
 */
public class BuildInfoJFrame extends javax.swing.JFrame
{
    static BufferedImage infoImage = null;
    {
        if (infoImage == null)
        {
            String file = "/Catan/Resource/card_build_info.png";
            
            try
            {
                infoImage = ImageIO.read(getClass().getResourceAsStream(file));
            }
            catch (Exception e)
            {
                System.err.println ("Failed loading image : " + file + " : " + e.toString());
            }                          
        }                 
    }         
            
    /** Creates new form BuildInfoJFrame */
    public BuildInfoJFrame ()
    {
        initComponents ();                   

        Insets i = this.getInsets();        
        
        int w = infoImage.getWidth()  + i.left + i.right;
        int h = infoImage.getHeight() + i.top  + i.bottom;
        
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-w)/2, (screenSize.height-h)/2, w, h);
    }
    
    public void resetSize()
    {
        Insets i = this.getInsets();        
        
        int w = infoImage.getWidth()  + i.left + i.right;
        int h = infoImage.getHeight() + i.top  + i.bottom;
                        
        this.setSize ( w, h);
    }     
       
    @Override
    public void paint (Graphics g)
    {
        Graphics2D g2 = (Graphics2D)g;
        
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);      
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR); 
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        
        if (infoImage != null)
        {                           
            Insets i = this.getInsets();
            
            g2.drawImage(infoImage, i.left, i.top, 
                    (this.getWidth()  - i.right)  - i.left, 
                    (this.getHeight() - i.bottom) - i.top, null, null);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catan Build Information");
        setName("Catan Build Information"); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 219, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 282, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized (java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentResized
    {//GEN-HEADEREND:event_formComponentResized
        this.repaint();
    }//GEN-LAST:event_formComponentResized

private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    if ( (evt.getClickCount() > 0) && 
        ((evt.getButton() == MouseEvent.BUTTON3) || (evt.getButton() == MouseEvent.BUTTON2)) )
    {
        this.dispose();
    }
}//GEN-LAST:event_formMouseClicked
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
