package Catan;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.Random;

/**
 *
 * @author  Steven De Toni
 * 
 *  April 2008
 */

public class DieJPanel extends javax.swing.JPanel
{    
	Random die            =  null;
    public Color bgColor  = Color.white;
    public Color dotColor = Color.black;
    int    currValue      = 0;
  
    /** Creates new form DieJPanel */
    public DieJPanel ()
    { 
        die = new Random();
        initComponents ();        
        rollDie();
    }
    
    public DieJPanel (int rndSeed)
    {
        die = new Random(rndSeed);
        initComponents ();        
        rollDie();
    }

    public void rollDie ()
    {
        currValue = die.nextInt(6)+1;        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 37, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 39, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void draw (Graphics g, int left, int top, int size)
    {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
            
       /*
        the die area is broken up into 9 equal squares,
        these are the variables to determine the center
        of each of the squares, the squares are labeled 
        as follows, going across the top: left, center, right
        going down: top, middle, bottom.
        */

        //the diameter of the points will be 1/8 of die size
        int diam = (size / 5);

        int radius = (diam / 2); // variable radius to be the radius
                     // of a point
        int x = left - radius;
        int y = top - radius;

        int leftTopX = (x + (size / 6)); 
        int leftTopY = (y + (size / 6));

        int rightTopX = (x + (size * 5) / 6);
        int rightTopY = (y + (size / 6));

        int leftMiddleX = (x + (size / 6));
        int leftMiddleY = (y + (size / 2));

        int centerMiddleX = (x + (size / 2));
        int centerMiddleY = (y + (size / 2));

        int rightMiddleX = (x + (size * 5) / 6);
        int rightMiddleY = (y + (size / 2));

        int leftBottomX = (x + (size / 6));
        int leftBottomY = (y + (size * 5) / 6);

        int rightBottomX = (x + (size * 5) / 6);
        int rightBottomY = (y + (size * 5) / 6);

        g2.setColor(bgColor);        
        g2.fillRoundRect(left, top, size, size, 8, 8);
        
        g2.setColor(Color.lightGray);
        g2.drawRoundRect(left, top, size-1, size-1, 8, 8);        
              
        g2.setColor(dotColor);
        
        switch (currValue)
        {
            case 1:
                //one point drawn
                g2.fillOval(centerMiddleX, centerMiddleY, diam, diam);
                break;
            case 2:
                //two points drawn
                g2.fillOval(leftTopX, leftTopY, diam, diam);
                g2.fillOval(rightBottomX, rightBottomY, diam, diam);
                break;
            case 3:
                //three points drawn
                g2.fillOval(centerMiddleX, centerMiddleY, diam, diam);
                g2.fillOval(leftTopX, leftTopY, diam, diam);
                g2.fillOval(rightBottomX, rightBottomY, diam, diam);
                break;
            case 4:
                //four points drawn
                g2.fillOval(leftTopX, leftTopY, diam, diam);
                g2.fillOval(rightTopX, rightTopY, diam, diam);
                g2.fillOval(leftBottomX, leftBottomY, diam, diam);
                g2.fillOval(rightBottomX, rightBottomY, diam, diam);
                break;
            case 5:
                //five points drawn
                g2.fillOval(leftTopX, leftTopY, diam, diam);
                g2.fillOval(rightBottomX, rightBottomY, diam, diam);
                g2.fillOval(rightTopX, rightTopY, diam, diam);
                g2.fillOval(leftBottomX, leftBottomY, diam, diam);
                g2.fillOval(centerMiddleX, centerMiddleY, diam, diam);
                break;
            case 6:
                //six points drawn
                g2.fillOval(leftTopX, leftTopY, diam, diam);
                g2.fillOval(rightBottomX, rightBottomY, diam, diam);
                g2.fillOval(rightTopX, rightTopY, diam, diam);
                g2.fillOval(leftBottomX, leftBottomY, diam, diam);
                g2.fillOval(leftMiddleX, leftMiddleY, diam, diam);
                g2.fillOval(rightMiddleX, rightMiddleY, diam, diam);
                break;
        }
    } 

    public void paintImmediately()
    {        
        super.paintImmediately(0, 0, this.getWidth(), this.getHeight());
    }
    
    @Override
	public void paint(Graphics g)
	{
        super.paint (g);
        draw (g, 0, 0, this.getWidth());        		
	}    
}
