package Catan;

import Catan.Partical.ExplodeTypes;
import Catan.Partical.ParticalCollection;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Polygon;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.random.RandomGenerator;
import java.util.random.RandomGeneratorFactory;
import javax.imageio.ImageIO;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author  Steven De Toni
 * 
 *  April 2008
 */
enum ObjSelectType
{

    NONE, ANY, TILE, BUILDPOINT, ROAD
};

public class GameBoardJPanel extends javax.swing.JPanel
{
    // ---- Game Map Data -----
    public LinkedList<Tile>       tileList  = new LinkedList<Tile>();
    public LinkedList<BuildPoint> buildList = new LinkedList<BuildPoint>();
    public LinkedList<Road>       roadList  = new LinkedList<Road>();
    
    // --- Background SEA image ---
    static BufferedImage bgImage = null;
        
    // ---- Scale/Grid Data ----
    float hexScale        = 1.0f;
    int   hexScaleWidth   = (1 << 15);
    int   hexLen          = 11;
    int   lastPaintWidth  = (1 << 15);
    int   lastPaintHeight = (1 << 15);
    
    // ----- Mouse Selection ----
    GameMouseNotifyInterf mouseNotifyObj = null;
    ObjSelectType         mouseSelObj    = ObjSelectType.NONE;    
    LinkedList<Polygon>   mouseSelList   = new LinkedList<Polygon>();
    
    // ----- Tile Render Level ----
    public boolean detailLevelHigh = true;
    CatanJFrame    gameWindow = null;

    // Single shared, high-quality generator for board generation (resource/port
    // tiles, dice numbers, initial robber, background). Reused instead of
    // allocating a new Random in each method. Note: board setup also runs at
    // panel construction time, before any GameRules exists, so this cannot defer
    // to GameRules.rand.
    private final RandomGenerator rand = RandomGeneratorFactory.of("L64X128MixRandom").create();

    // ----- High-Light Build/Selection ----
    public boolean hlAssistActive  = true;
    boolean        hlRender        = false;
    Player         hlLastPlayer    = null;
    Point          hlLastMouseTest = new Point(0,0);
    CatanGraphBase hlLastSelObj    = null;
    CatanGraphBase hlPopMenuObj    = null;

    // ----- Flash game board changes -----
    // The freshly changed object (building/road/robbed tile) that is currently
    // being flashed, and whether the flash highlight is drawn in this frame.
    CatanGraphBase blinkObj        = null;
    boolean        blinkOn         = false;

    // ----- Quicken board refresh/updates -----
    BufferedImage saveTileBG       = null;
    
    // ------------------------------------
    private void initGameBoard()
    {
        // Load some images
        if (bgImage == null)
        {
            final RandomGenerator r = this.rand;
            
            String files[] = {"/Catan/Resource/bg_3.jpg", "/Catan/Resource/bg_4.jpg",
                              "/Catan/Resource/bg_5.gif", "/Catan/Resource/bg_6.gif"
                             };
            String f = files[r.nextInt(files.length)];
            
            try
            {
                bgImage = ImageIO.read(getClass().getResourceAsStream(f));
            }
            catch (Exception e)
            {
                System.err.println ("Failed loading image : " + f + " : " + e.toString());
                System.exit(1);
            }
        }
        
        initComponents();
        this.buildInitialCatanScene (GameTypes.STANDARD4, GameVariants.NORMAL, false, false);               
    }

    public GameBoardJPanel()
    {
        initGameBoard();
    }

    /** Creates new form GameBoardJPanel */
    public GameBoardJPanel(CatanJFrame gameWindow)
    {
        this.gameWindow     = gameWindow;
        initGameBoard();
    }

    /** Creates new form GameBoardJPanel */
    public GameBoardJPanel(CatanJFrame gameWindow, boolean hlAssistActive)
    {
        this.gameWindow     = gameWindow;
        this.hlAssistActive = hlAssistActive;
        initGameBoard();
    }
    
    public void Debug (String s, DebugLevel dl)
    {
        if (gameWindow != null)
        {
            gameWindow.Debug(s, dl);
        }
    }

    public void DebugErr(String s)
    {
        if (gameWindow != null)
        {
            gameWindow.DebugErr(s);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(164, 191, 231));
        setDoubleBuffered(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 445, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // ----------------------------------------------------------------------
    public void setMouseSelectionType(GameMouseNotifyInterf notifyObj, ObjSelectType ost)
    {
        mouseNotifyObj = notifyObj;
        mouseSelObj    = ost;
    }

    public void clearHighlightAssist ()
    {if (hlRender != false)
            this.repaint();
                    
        
        hlLastPlayer   = null;
        hlRender       = false;
        hlLastSelObj   = null;
        mouseSelObj    = ObjSelectType.NONE;
        mouseNotifyObj = null;        
    }
    
    private void formMouseClicked (java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseClicked
    {//GEN-HEADEREND:event_formMouseClicked
        if (gameWindow == null)
            return;
                
        if ((mouseSelObj == ObjSelectType.NONE) && (hlLastSelObj != null))
        {
            //Create the popup menu.
            JPopupMenu pMenu = new JPopupMenu();
            JMenuItem  mi    = null;

            // Build a road?
            if (hlLastSelObj instanceof Road)
            {
                hlPopMenuObj = hlLastSelObj;
                mi = new JMenuItem ("Build Road?");
                pMenu.add (mi);                
                
                mi.addActionListener(new java.awt.event.ActionListener() 
                {
                    public void actionPerformed(java.awt.event.ActionEvent evt) 
                    {
                        try
                        {
                            //System.out.println ("Build Road!");
                            clearHighlightAssist ();
                            gameWindow.gameRules.thisPlayer.buildObject(CanBuildTypes.ROAD, hlPopMenuObj);
                        }
                        catch (Exception e)
                        {
                        }                                                                    
                    }
                });                                                                                               
            }            
            else if (hlLastSelObj instanceof BuildPoint) // Build a settlement/city ?
            {
                // determine if upgrading a city of building a settlement!
                // check if we can build a settlement...                
                if ((this.gameWindow.gameRules.isValidBuildPoint ((BuildPoint)hlLastSelObj, true, this.gameWindow.gameRules.thisPlayer, false) != false) &&
                    (this.gameWindow.gameRules.thisPlayer.canBuild(CanBuildTypes.SETTLEMENT) > 0))    
                {
                    hlPopMenuObj = hlLastSelObj;
                    mi = new JMenuItem ("Build Settlement?");
                    pMenu.add (mi);                

                    mi.addActionListener(new java.awt.event.ActionListener() 
                    {
                        public void actionPerformed(java.awt.event.ActionEvent evt) 
                        {
                            //System.out.println ("Build a Settlement!");
                            try
                            {         
                                clearHighlightAssist ();                                
                                gameWindow.gameRules.thisPlayer.buildObject(CanBuildTypes.SETTLEMENT, hlPopMenuObj);
                            }
                            catch (Exception e)
                            {
                            }                                        
                        }
                    });                                            
                }                
                // or upgrade to a city ... 
                else if ((this.gameWindow.gameRules.thisPlayer.canBuild(CanBuildTypes.CITY) > 0)   &&
                        (((BuildPoint)hlLastSelObj).owner == this.gameWindow.gameRules.thisPlayer) &&
                        (((BuildPoint)hlLastSelObj).type  == BuildPointTypes.SETTLEMENT))
                {
                    hlPopMenuObj = hlLastSelObj;
                    mi = new JMenuItem ("Build City?");
                    pMenu.add (mi);                

                    mi.addActionListener(new java.awt.event.ActionListener() 
                    {
                        public void actionPerformed(java.awt.event.ActionEvent evt) 
                        {
                            try
                            {
                                clearHighlightAssist ();                                
                                gameWindow.gameRules.thisPlayer.buildObject(CanBuildTypes.CITY, hlPopMenuObj);
                                //System.out.println ("Build a City!");
                            }
                            catch (Exception e)
                            {
                            }                                                                        
                        }
                    });    
                }                
            }
  
            pMenu.show(evt.getComponent(), evt.getX(), evt.getY());            
        }  
        
        LinkedList<Object> l = new LinkedList<Object>();
        mouseSelList.clear();

        Iterator item;

        if ((mouseSelObj == ObjSelectType.ANY) || (mouseSelObj == ObjSelectType.TILE))
        {
            l.add((Object) tileList);
        }
        if ((mouseSelObj == ObjSelectType.ANY) || (mouseSelObj == ObjSelectType.BUILDPOINT))
        {
            l.add((Object) buildList);
        }
        if ((mouseSelObj == ObjSelectType.ANY) || (mouseSelObj == ObjSelectType.ROAD))
        {
            l.add((Object) roadList);
        // Process the list ....
        }
        Iterator il = l.iterator();
        Polygon p;

        while (il.hasNext())
        {
            LinkedList iItem = (LinkedList) il.next();

            item = iItem.iterator();

            while (item.hasNext())
            {
                p = (Polygon) item.next();

                if (p.contains(evt.getPoint()) != false)
                {
                    mouseSelList.add(p);
                    break;
                }
            }
        }

        // Send a notification to the parent form, we have processed a mouse event.
        if ((mouseSelObj != ObjSelectType.NONE) && (mouseSelList.size() > 0))
        {
            mouseNotifyObj.GMNI_MouseSelectEvent(this, mouseSelList, mouseSelObj);
        }
    }//GEN-LAST:event_formMouseClicked

private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
       
        if (gameWindow == null)
            return;

        if (hlAssistActive == false)
            return;
        
        boolean clearSelObj = false;
        boolean setSelObj   = false;
        
        if (this.gameWindow.gameRules == null)
            return;
        
        if (this.gameWindow.gameRules.thisPlayer == null)
            return;
        
        if (this.gameWindow.gameRules.thisPlayer.type == PlayerTypes.COMPUTER) 
        {
            if (hlRender != false)
            {
                hlLastPlayer = null;
                hlRender     = false;
                hlLastSelObj = null;
                this.repaint();
            }      
            return;            
        }
        
        if (this.gameWindow.gameRules.thisPlayer != hlLastPlayer) 
        {
            hlLastPlayer = null;
            hlRender     = false;
            hlLastSelObj = null;
            this.repaint();            
        }
        
        CatanGraphBase selObj = null;
        LinkedList<Object> l = new LinkedList<Object>();
        Iterator item;

        switch (mouseSelObj)
        {
            case BUILDPOINT:
                l.add((Object) buildList);
                break;

            case ROAD:
                l.add((Object) roadList);
                break;               

            default: // if no in restricted build mode and the high-light areas in 
                     // gameboard you can build/upgrade.
                switch (gameWindow.gameRules.gamePhase)                
                {
                    case PLACE_ROBBER:
                        l.add ((Object)tileList);
                        break;
                        
                    default:
                        // Check if this player can build stuff ..
                        if ((this.gameWindow.gameRules.thisPlayer.canBuild(CanBuildTypes.CITY)       > 0) || 
                            (this.gameWindow.gameRules.thisPlayer.canBuild(CanBuildTypes.SETTLEMENT) > 0))
                            l.add((Object) buildList);

                        if (this.gameWindow.gameRules.thisPlayer.canBuild(CanBuildTypes.ROAD) > 0)
                            l.add((Object) roadList);
                }
        }

        // Process the list ....
        Iterator       il     = l.iterator();
        Polygon p;

        while (il.hasNext() && (selObj == null))
        {
            LinkedList iItem = (LinkedList) il.next();

            item = iItem.iterator();

            while (item.hasNext())
            {
                p = (Polygon) item.next();

                if (p.contains(evt.getPoint()) != false)
                {
                    selObj = (CatanGraphBase)p;
                    break;
                }
            }            
        }             
                        
        // check if object has changed and is a valid selection
        if ((selObj != null) && (selObj != hlLastSelObj))
        {            
            if (selObj instanceof BuildPoint) // high-light buiild areas
            {                             
                switch (this.gameWindow.gameRules.gamePhase)
                {
                    case START_PLACEMENT_1:
                    case START_PLACEMENT_2:
                        // check if we can build a settlement...                
                        if (this.gameWindow.gameRules.isValidBuildPoint ((BuildPoint)selObj, false, this.gameWindow.gameRules.thisPlayer, false) != false)                    
                        {
                            setSelObj = true;
                        } 
                        else
                            clearSelObj = true;
                        break;
                    default:
                        // check if we can build a settlement...                
                        if ((this.gameWindow.gameRules.isValidBuildPoint ((BuildPoint)selObj, true, this.gameWindow.gameRules.thisPlayer, false) != false) &&
                            (this.gameWindow.gameRules.thisPlayer.canBuild(CanBuildTypes.SETTLEMENT) > 0) && 
                            (this.gameWindow.gameRules.thisPlayer.bldStckSettlement > 0))    
                        {
                            setSelObj = true;
                        }                
                        // or upgrade to a city ... 
                        else if ((this.gameWindow.gameRules.thisPlayer.canBuild(CanBuildTypes.CITY) > 0) &&
                                (((BuildPoint)selObj).owner == this.gameWindow.gameRules.thisPlayer)     &&
                                (((BuildPoint)selObj).type  == BuildPointTypes.SETTLEMENT)               &&
                                  (this.gameWindow.gameRules.thisPlayer.bldStckCity > 0))
                        {
                            setSelObj = true;
                        }
                        else
                            clearSelObj = true;                        
                }
            }
            else if (selObj instanceof Road) // high-light road areas 
            {           
                if ((this.gameWindow.gameRules.isValidRoadBuild((Road)selObj, this.gameWindow.gameRules.thisPlayer) != false) &&
                    (this.gameWindow.gameRules.thisPlayer.bldStckRoad > 0))
                    setSelObj = true;
                else
                    clearSelObj = true;
            }           
            else if (selObj instanceof Tile) // Move Robber ... 
            {
                    switch (((Tile)(selObj)).type)
                    {
                        case WOOD:
                        case ROCK:
                        case SHEEP:
                        case WHEAT:
                        case BRICK:
                        case VAR_VOLCANO:
                            if (((Tile)selObj).hasRobber != false)
                                clearSelObj = true;
                            else
                                setSelObj = true;
                            break;
                        default:
                            clearSelObj = true;
                    }
                
            }
            
        }
        else if ((hlRender != false) && (selObj != hlLastSelObj))
            clearSelObj = true;
       
        if (clearSelObj != false)
        {
            hlLastPlayer = null;
            hlRender     = false;
            hlLastSelObj = null;
            this.repaint();                    
        }   
        
        if (setSelObj != false)
        {
            hlLastPlayer = this.gameWindow.gameRules.thisPlayer;
            hlRender     = true;
            hlLastSelObj = selObj;
            this.repaint();            
        }
}//GEN-LAST:event_formMouseMoved

    // ******************** Build Map Infomtion *******************************
    public void addUniqueRoardPoints(Tile t)
    {
        Point pt = new Point();
        int boxLen = (int) (hexScale / 5.0f);

        for (int idx = 0; idx < t.npoints; idx++)
        {
            int idx2 = idx - 1;

            if (idx2 < 0)
            {
                idx2 = t.npoints + idx2;
            }
            pt.x = t.xpoints[idx2] + ((t.xpoints[idx] - t.xpoints[idx2]) / 2);
            pt.y = t.ypoints[idx2] + ((t.ypoints[idx] - t.ypoints[idx2]) / 2);

            boolean allocate = true;

            for (Road r : roadList)
            {
                // If it exits, then don't store it
                if (r.contains(pt) != false)
                {
                    t.addRoadJoin(r); // Associate this tile to this road.
                    r.addTileJoin(t); // Associate this road to rhis tile.

                    allocate = false;
                    break;
                }
            }

            // Create a new build point.                           
            if (allocate != false)
            {
                Road r = new Road((Object) this);

                if (t.ypoints[idx2] > t.ypoints[idx])
                {
                    r.addPoint(t.xpoints[idx2] - boxLen, t.ypoints[idx2] + boxLen);
                    r.addPoint(t.xpoints[idx2] + boxLen, t.ypoints[idx2] + boxLen);
                    r.addPoint(t.xpoints[idx] + boxLen, t.ypoints[idx] - boxLen);
                    r.addPoint(t.xpoints[idx] - boxLen, t.ypoints[idx] - boxLen);
                }
                else if (t.ypoints[idx2] == t.ypoints[idx])
                {
                    if (t.xpoints[idx] < t.xpoints[idx2])
                    {
                        r.addPoint(t.xpoints[idx] - boxLen, t.ypoints[idx] - boxLen);
                        r.addPoint(t.xpoints[idx] - boxLen, t.ypoints[idx] + boxLen);
                        r.addPoint(t.xpoints[idx2] + boxLen, t.ypoints[idx2] + boxLen);
                        r.addPoint(t.xpoints[idx2] + boxLen, t.ypoints[idx2] - boxLen);
                    }
                    else
                    {
                        r.addPoint(t.xpoints[idx] + boxLen, t.ypoints[idx] - boxLen);
                        r.addPoint(t.xpoints[idx] + boxLen, t.ypoints[idx] + boxLen);
                        r.addPoint(t.xpoints[idx2] - boxLen, t.ypoints[idx2] + boxLen);
                        r.addPoint(t.xpoints[idx2] - boxLen, t.ypoints[idx2] - boxLen);
                    }
                }
                else
                {
                    r.addPoint(t.xpoints[idx] - boxLen, t.ypoints[idx] + boxLen);
                    r.addPoint(t.xpoints[idx] + boxLen, t.ypoints[idx] + boxLen);
                    r.addPoint(t.xpoints[idx2] + boxLen, t.ypoints[idx2] - boxLen);
                    r.addPoint(t.xpoints[idx2] - boxLen, t.ypoints[idx2] - boxLen);
                }

                t.addRoadJoin(r); // Associate this tile to this road.

                r.addTileJoin(t); // Associate this road to rhis tile.

                roadList.add(r);
            }
        }
    }

    public void addUniqueBuildPoints(Tile t)
    {
        Point pt = new Point();
        int boxLen = (int) (hexScale / 5.0f);

        for (int idx = 0; idx < t.npoints; idx++)
        {
            pt.x = t.xpoints[idx];
            pt.y = t.ypoints[idx];

            boolean allocate = true;
            for (BuildPoint bp : buildList)
            {
                // If it exits, then don't store it
                if (bp.contains(pt) != false)
                {
                    t.addBuildPointJoin(bp); // Associate this tile to this build point.

                    bp.addTileJoin(t);       // Assocaute this build point to this tile.

                    allocate = false;
                    break;
                }
            }

            // Create a new build point.                           
            if (allocate != false)
            {
                BuildPoint bp = new BuildPoint((Object) this);
                bp.addPoint(t.xpoints[idx] - boxLen, t.ypoints[idx] - boxLen);
                bp.addPoint(t.xpoints[idx] - boxLen, t.ypoints[idx] + boxLen);
                bp.addPoint(t.xpoints[idx] + boxLen, t.ypoints[idx] + boxLen);
                bp.addPoint(t.xpoints[idx] + boxLen, t.ypoints[idx] - boxLen);

                t.addBuildPointJoin(bp); // Associate this tile to this build point.

                bp.addTileJoin(t);       // Assocaute this build point to this tile.

                buildList.add(bp);
            }
        }
    }
    
    // Search port tiles with 3 buildable port points and reduce them to 2 buildable ports
    // base upon : A port build point should have at least 1 instance of 2 spaces to next port build point.      
    public void linkBuildPointsToPorts()
    {
        // Find port tiles and make the buildpoints buildable ports
        for (Tile t : tileList)
        {
            switch (t.type)
            {
                default:
                    continue;

                case PORT_ANY_3TO1:
                case PORT_BRICK_2TO1:
                case PORT_ROCK_2TO1:
                case PORT_WHEAT_2TO1:
                case PORT_WOOD_2TO1:
                case PORT_SHEEP_2TO1:
                    break;
            }

            for (BuildPoint bp : buildList)
            {
                // If null then continue, otherwise make it a port
                if (bp.type == BuildPointTypes.NULL)
                {
                    continue;
                }
                if (bp.tileJoins.contains(t) != false)
                {
                    bp.setPort(t.type);
                }
            }
        }

        // Find tiles with 4 ports and remove 2 ports.          
        LinkedList<Tile> reducePortsList = new LinkedList<Tile>();
        for (Tile t : tileList)
        {
            int portCount = 0;

            for (BuildPoint bp : t.buildJoins)
            {
                // If null then continue, otherwise make it a port
                if (bp.isPort != false)
                {
                    portCount++;
                }
            }

            if (portCount >= 4)
            {
                reducePortsList.add(t);
            }
        }

        // With these ports, reduce them by 2 ports, make them only buildable.        
        LinkedList<BuildPoint> buildPointReduceList = new LinkedList<BuildPoint>();
        for (Tile t : reducePortsList)
        {
            for (BuildPoint bp : t.buildJoins)
            {
                // If null then continue, otherwise make it a port
                if (bp.isPort != false)
                {
                    int removeCount = 0;

                    for (Road r : bp.roadJoins)
                    {
                        BuildPoint rBP1 = (BuildPoint) r.buildJoins.get(0);
                        BuildPoint rBP2 = (BuildPoint) r.buildJoins.get(1);

                        boolean b1 = rBP1.tileJoins.contains(t);
                        boolean b2 = rBP2.tileJoins.contains(t);
                        if ((rBP1.tileJoins.contains(t) == false) || (rBP2.tileJoins.contains(t) == false))
                        {
                            continue;
                        }
                        if (rBP1 == bp)
                        {
                            if (rBP2.isPort != false)
                            {
                                removeCount++;
                            }
                        }
                        else
                        {
                            if (rBP1.isPort != false)
                            {
                                removeCount++;
                            }
                        }
                    }

                    if (removeCount >= 2)
                    {
                        buildPointReduceList.add(bp);
                    }
                }
            }
        }

        // Reduce/make these buildpoint, normal land build points.
        for (BuildPoint bp : buildPointReduceList)
        {
            bp.type     = BuildPointTypes.BUILDABLE_LAND;
            bp.isPort   = false;
            bp.portType = TileTypes.NULL;
        }
        
        // check if there are tiles with 3 ports, and make them 2 ports in a 
        // 6 player game board
        for (Tile t:tileList)
        {
            int portCount = 0;
            for (BuildPoint bp:t.buildJoins)
            {
                if (bp.isPort != false)
                    portCount++;
            }
            
            if (portCount >= 3)
            {
                for (BuildPoint bp:t.buildJoins)
                {
                    if (bp.isPort != false)
                    {
                        int portDups = 0;
                        for (Road r:bp.roadJoins)
                        {
                            for (BuildPoint bp2:r.buildJoins)
                            {
                                if ((bp2 != bp) && (bp2.isPort != false))
                                    portDups++;
                            }
                        }
                        if (portDups <= 1)
                        {
                            bp.isPort = false;
                            break;
                        }
                    }
                }
            }
        }
    }

    public void linkBuildPointsToRoads()
    {
        for (Road r : roadList)
        {
            for (BuildPoint bp : buildList)
            {
                // If it exits, then reference it
                if (r.contains(bp.getCentrePoint()) != false)
                {
                    r.addBuildPointJoin(bp);
                    bp.addRoadJoin(r);
                }
            }

            // update road buldiable statue/type.
            if (Road.isBuildableRoad(r) != false)
            {
                r.type = RoadTypes.BUILDABLE;
            }
        }
    }
    
    public Tile setRobberInitLoc ()
    {
        final RandomGenerator r = this.rand;
        
        // Clear current robber settings
        int whichTile = 0;
        for (Tile t:tileList)
        {
            switch (t.type)
            {
                case DESERT:
                case VAR_VOLCANO:
                    whichTile++;
            }
            
            t.hasRobber = false;
        }
        
        whichTile = r.nextInt(whichTile);

        // Add the robber to its desert/volcano home
        for (Tile t:tileList)
        {
            switch (t.type)
            {
                case DESERT:
                case VAR_VOLCANO:
                    
                    if (whichTile <= 0)
                    {
                        t.hasRobber = true;
                        return t;
                    }
                    whichTile--;
            }
        }
        return null;
    }
    
    public void randomiseEvenlyDiceRolls (GameTypes boardType, GameVariants gameVariant)
    {
        final RandomGenerator r = this.rand;

        // Dice Rolls ...
        //                        2  3  4  5  6  7  8  9 10 11 12
        int diceScore[] =
        {
            1, 2, 3, 4, 5, 0, 5, 4, 3, 2, 1
        };
        LinkedList<Integer> nl = new LinkedList<Integer>();

        for (int wholeRetry = 1; wholeRetry <= 15; wholeRetry++)
        {
            // Clear tiles dice roll values. 
            for (Tile t : tileList)
            {
                switch (t.type)
                {
                    case BRICK:
                    case ROCK:
                    case WHEAT:
                    case WOOD:
                    case SHEEP:
                        t.diceRoll      = 0;
                        t.diceRollScore = 0;
                        break;
                }
            }
                        
            // Create numbers list
            nl.clear();
            switch (boardType)
            {
                case STANDARD4:                                
                    nl.add(Integer.valueOf(2)); nl.add(Integer.valueOf(3)); nl.add(Integer.valueOf(3)); nl.add(Integer.valueOf(4));
                    nl.add(Integer.valueOf(4)); nl.add(Integer.valueOf(5)); nl.add(Integer.valueOf(5)); nl.add(Integer.valueOf(6));
                    nl.add(Integer.valueOf(6)); nl.add(Integer.valueOf(8)); nl.add(Integer.valueOf(8)); nl.add(Integer.valueOf(9));
                    nl.add(Integer.valueOf(9)); nl.add(Integer.valueOf(10));nl.add(Integer.valueOf(10));nl.add(Integer.valueOf(11));
                    nl.add(Integer.valueOf(11));nl.add(Integer.valueOf(12));
                    break;
                    
               case STANDARD6_NO_ENDTURNBLD:
               case STANDARD6_ENDTURNBLD:                           
                    nl.add(Integer.valueOf(2)); nl.add(Integer.valueOf(2)); 
                    nl.add(Integer.valueOf(3)); nl.add(Integer.valueOf(3)); nl.add(Integer.valueOf(3));
                    nl.add(Integer.valueOf(4)); nl.add(Integer.valueOf(4)); nl.add(Integer.valueOf(4));
                    nl.add(Integer.valueOf(5)); nl.add(Integer.valueOf(5)); nl.add(Integer.valueOf(5)); 
                    nl.add(Integer.valueOf(6)); nl.add(Integer.valueOf(6)); nl.add(Integer.valueOf(6));
                    nl.add(Integer.valueOf(8)); nl.add(Integer.valueOf(8)); nl.add(Integer.valueOf(8));
                    nl.add(Integer.valueOf(9)); nl.add(Integer.valueOf(9)); nl.add(Integer.valueOf(9)); 
                    nl.add(Integer.valueOf(10));nl.add(Integer.valueOf(10));nl.add(Integer.valueOf(10));
                    nl.add(Integer.valueOf(11));nl.add(Integer.valueOf(11));nl.add(Integer.valueOf(11));
                    nl.add(Integer.valueOf(12));nl.add(Integer.valueOf(12));
                    break;
            }
            
            // add dice rolls to Variant tiles.
            switch (gameVariant)
            {
                case VOLCANO:
                    break;
            }

            boolean wholeRedo = false;
            for (Tile t : tileList)
            {
                switch (t.type)
                {
                    case BRICK:
                    case ROCK:
                    case WHEAT:
                    case WOOD:
                    case SHEEP:
                    case VAR_VOLCANO:
                        int dval            = 0;
                        int idx             = 0;
                        int partialRetry    = -1;
                        boolean partialRedo = false;

                        do
                        {                            
                            partialRedo = false;
                            partialRetry++;

                            if (wholeRetry < 15) // if after 15 tries still can't get it correct, give up 
                            {                                                                
                                // Add custom dice roll to Variant tile.
                                switch (t.type)
                                {                                    
                                    case VAR_VOLCANO:
                                        if (r.nextBoolean())            // 50/50 between low (4-6) and high (8-10) values
                                            dval = 4 + r.nextInt(3);
                                        else
                                            dval = 8 + r.nextInt(3);
                                        break;
                                        
                                    default:
                                        idx  = r.nextInt(nl.size());
                                        dval = ((Integer) nl.get(idx)).intValue(); // Dont match 6's and 8's next to each other.
                                }                                       
                                
                                switch (dval)
                                {
                                    case 6:
                                    case 8:
                                        for (BuildPoint bp : t.buildJoins)
                                        {
                                            for (Tile testTile : bp.tileJoins)
                                            {
                                                switch (testTile.diceRoll)
                                                {
                                                    case 6:
                                                    case 8:
                                                        partialRedo = true;
                                                        Debug("GameBoardJPanel.randomiseDiceRolls: Die Roll [" + wholeRetry + "](" + partialRetry + ") : conflicting " + dval + " -> " + testTile.diceRoll, DebugLevel.COMPLETE);
                                                        break;
                                                }
                                                if (partialRedo != false)
                                                {
                                                    break;
                                                }
                                            }
                                            if (partialRedo != false)
                                            {
                                                break;
                                            }
                                        }
                                }
                            }
                        }
                        while ((partialRedo != false) && (partialRetry < 30));

                        if (partialRetry >= 30)
                        {
                            wholeRedo = true;
                        }
                        
                        // Add custom dice roll to Variant tile.
                        switch (t.type)
                        {                                    
                            case VAR_VOLCANO:
                                t.diceRoll      = dval;
                                t.diceRollScore = diceScore[t.diceRoll - 2];                                
                                break;                                                                              
                            default:
                                t.diceRoll      = ((Integer) nl.remove(idx)).intValue();
                                t.diceRollScore = diceScore[t.diceRoll - 2];                                
                        }                                                                       
                        break;
                }
                if (wholeRedo != false)
                {
                    Debug("GameBoardJPanel.randomiseDiceRolls: Need to do a whole redo [" + (wholeRetry + 1) + "]", DebugLevel.COMPLETE);
                    break;
                }
            }

            if (wholeRedo == false)
            {
                break;
            }
        }        
    }
   
    public void randomiseEvenlyResourceTiles ()
    {
        final RandomGenerator r = this.rand;
        LinkedList<TileTypes> tileTypesList = new LinkedList<TileTypes>();

        for (int wholeRetry = 1; wholeRetry <= 15; wholeRetry++)
        {
            // Reset Tiles...            
            for (Tile t : tileList)
            {
                switch (t.type)
                {
                    case BRICK:
                    case ROCK:
                    case WHEAT:
                    case WOOD:
                    case SHEEP:
                    case DESERT:
                    case VAR_VOLCANO:
                        tileTypesList.add(t.type);
                        t.type = TileTypes.NULL;
                        t.hasRobber = false;
                }
            }
            
            boolean wholeRedo = false;
            
            for (Tile t : tileList)
            {
                if (t.type != TileTypes.NULL)
                    continue;
                
                int idx;
                int partialRetry = -1;
                boolean partialRedo = false;

                do
                {
                    idx = r.nextInt(tileTypesList.size());
                    partialRedo = false;
                    partialRetry++;

                    if (wholeRetry < 15) // if after 15 tries still can't get it correct, give up 
                    {
                        // Dont match 6's and 8's next to each other.
                        TileTypes tVal = (TileTypes)tileTypesList.get(idx);
                                                
                        for (BuildPoint bp : t.buildJoins)
                        {
                            for (Tile testTile : bp.tileJoins)
                            {
                                if (testTile.type == tVal)
                                {
                                    partialRedo = true;
                                    Debug("GameBoardJPanel.randomiseResourceTiles: Tile Placement [" + wholeRetry + "](" + partialRetry + ") : conflicting " + tVal.name() + " -> " + testTile.type.name(), DebugLevel.COMPLETE);
                                    break;
                                }
                            }
                            if (partialRedo != false)
                                break;
                        }
                    }
                }
                while ((partialRedo != false) && (partialRetry < 30));

                if (partialRetry >= 30)
                {
                    wholeRedo = true;
                }
                            
                t.type = (TileTypes) tileTypesList.remove(idx);
                

                              
                if (wholeRedo != false)
                {
                    Debug("GameBoardJPanel.randomiseResourceTiles: Need to do a whole redo [" + (wholeRetry + 1) + "]", DebugLevel.COMPLETE);
                    break;
                }
            }

            if (wholeRedo == false)
            {
                break;
            }
        }        
    }     
    
    //***************************************************************************************
    public void randomiseCatanScene(boolean evenlyRandResTiles, boolean evenlyRandPortTiles)
    {
        // Randomise dice numbers on tiles... 
        final RandomGenerator r = this.rand;        

        if (evenlyRandResTiles != false)
            randomiseEvenlyResourceTiles ();   
        else
        {
            LinkedList<TileTypes> tileTypesList = new LinkedList<TileTypes>();
            
            // Randomise Resource Tiles, most randomly 
            for (Tile t : tileList)
            {
                switch (t.type)
                {
                    case BRICK:
                    case ROCK:
                    case WHEAT:
                    case WOOD:
                    case SHEEP:
                    case DESERT:
                    case VAR_VOLCANO:
                        tileTypesList.add(t.type);
                        t.type = TileTypes.NULL;
                        t.hasRobber = false;
                }
            }
            
            for (Tile t : tileList)
            {
                if (t.type == TileTypes.NULL)
                    t.type = (TileTypes) tileTypesList.remove(r.nextInt(tileTypesList.size()));
            }
        }               
                
        // Randomise Port Tiles... 
        LinkedList<TileTypes> tileTypesList = new LinkedList<TileTypes>();
        for (Tile t : tileList)
        {
            switch (t.type)
            {
                case PORT_ANY_3TO1:
                  if (evenlyRandPortTiles != false)
                      break;                       
                case PORT_BRICK_2TO1:
                case PORT_ROCK_2TO1:
                case PORT_WHEAT_2TO1:
                case PORT_WOOD_2TO1:
                case PORT_SHEEP_2TO1:
                    tileTypesList.add(t.type);
                    t.type = TileTypes.NULL;
            }
        }

        for (Tile t : tileList)
        {
            if (t.type == TileTypes.NULL)
                t.type = (TileTypes) tileTypesList.remove(r.nextInt(tileTypesList.size()));
        }
    }

    public void buildInitialCatanScene (GameTypes boardType, GameVariants gameVariant, boolean evenlyRandResTiles, boolean evenlyRandPortTiles)
    {
        tileList.clear();
        buildList.clear();
        roadList.clear();

        switch (boardType)
        {           
            case STANDARD4:
            {
                // ---- Calc Scale ----        
                hexLen   = 11;
                hexScale = (float) hexScaleWidth / (float) hexLen;

                float xPlotPos = 0;
                float yPlotPos = hexScale / 2.0f;

                TileTypes[][] scene =
                {
                    {TileTypes.SEA,             TileTypes.SEA,             TileTypes.PORT_WHEAT_2TO1, TileTypes.WOOD,         TileTypes.PORT_ANY_3TO1, TileTypes.SEA,            TileTypes.SEA            },
                    {TileTypes.PORT_ANY_3TO1,   TileTypes.WHEAT,           TileTypes.SHEEP,          TileTypes.ROCK,          TileTypes.BRICK,         TileTypes.WOOD,           TileTypes.PORT_WOOD_2TO1 },
                    {TileTypes.SEA,             TileTypes.SHEEP,           TileTypes.WOOD,           TileTypes.BRICK,         TileTypes.WHEAT,          TileTypes.SHEEP,          TileTypes.SEA            },
                    {TileTypes.PORT_SHEEP_2TO1, TileTypes.ROCK,            TileTypes.DESERT,         TileTypes.SHEEP,         TileTypes.WOOD,          TileTypes.WHEAT,           TileTypes.PORT_ANY_3TO1  },
                    {TileTypes.SEA,             TileTypes.PORT_BRICK_2TO1, TileTypes.BRICK,          TileTypes.WHEAT,         TileTypes.ROCK,          TileTypes.PORT_ROCK_2TO1, TileTypes.SEA            },
                    {TileTypes.SEA,             TileTypes.SEA,             TileTypes.SEA,            TileTypes.PORT_ANY_3TO1, TileTypes.SEA,           TileTypes.SEA,            TileTypes.SEA            },
                };

                for (int y = 0; y < 6; y++)
                {
                    xPlotPos = hexScale / 2.0f;

                    for (int x = 0; x < 7; x++)
                    {
                        Tile t = new Tile((Object) this);

                        t.addPoint((int) (-1.0f * hexScale), (int) (0.0f * hexScale));
                        t.addPoint((int) (-0.5f * hexScale), (int) (1.0f * hexScale));
                        t.addPoint((int) (0.5f * hexScale), (int) (1.0f * hexScale));
                        t.addPoint((int) (1.0f * hexScale), (int) (0.0f * hexScale));
                        t.addPoint((int) (0.5f * hexScale), (int) (-1.0f * hexScale));
                        t.addPoint((int) (-0.5f * hexScale), (int) (-1.0f * hexScale));

                        t.translate((int) (hexScale / 2.0f) + (int) xPlotPos,
                                    (int) (hexScale / 2.0f) + (int) yPlotPos);

                        xPlotPos += hexScale * 1.5f;

                        if (x % 2 == 0)
                        {
                            yPlotPos += hexScale;
                        }
                        else
                        {
                            yPlotPos -= hexScale;
                        }
                        tileList.add(t);

                        t.type = scene[y][x];

                        // Construct mappings and game rule/constuction objects
                        this.addUniqueBuildPoints(t);
                        this.addUniqueRoardPoints(t);

                        // Add the robber if this is the desert
                        if (t.type == TileTypes.DESERT)
                        {
                            t.hasRobber = true;
                        }
                    }

                    yPlotPos += hexScale;
                }

                // Process/replace with Variant tiles
                switch (gameVariant)
                {
                    case VOLCANO:
                        // swap desert to volcano tile
                        for (Tile t:tileList)
                        {
                            if (t.type == TileTypes.DESERT)
                                t.type = TileTypes.VAR_VOLCANO;
                        }
                        break;
                }

                this.linkBuildPointsToRoads   ();
                this.randomiseCatanScene      (evenlyRandResTiles, evenlyRandPortTiles);
                this.randomiseEvenlyDiceRolls (boardType, gameVariant);
                this.linkBuildPointsToPorts   ();                    
            }
            break;
                
            case STANDARD6_NO_ENDTURNBLD:
            case STANDARD6_ENDTURNBLD:
            {
                // ---- Calc Scale ----        
                hexLen   = 14;
                hexScale = (float) hexScaleWidth / (float) hexLen;

                float xPlotPos = 0;
                float yPlotPos = hexScale / 2.0f;
                   
                TileTypes[][] scene =
                {
                    {TileTypes.SEA,             TileTypes.SEA,             TileTypes.SEA,            TileTypes.PORT_ANY_3TO1,   TileTypes.SHEEP,          TileTypes.PORT_BRICK_2TO1, TileTypes.SEA,            TileTypes.SEA,            TileTypes.SEA            },
                    {TileTypes.SEA,             TileTypes.PORT_WOOD_2TO1,  TileTypes.WOOD,           TileTypes.WOOD,            TileTypes.BRICK,          TileTypes.SHEEP,           TileTypes.WHEAT,          TileTypes.PORT_ANY_3TO1,  TileTypes.SEA            },
                    {TileTypes.PORT_ANY_3TO1,   TileTypes.ROCK,            TileTypes.WHEAT,          TileTypes.WOOD,            TileTypes.WHEAT,           TileTypes.SHEEP,           TileTypes.BRICK,         TileTypes.ROCK,           TileTypes.PORT_ROCK_2TO1 },
                    {TileTypes.SEA,             TileTypes.DESERT,          TileTypes.ROCK,           TileTypes.ROCK,            TileTypes.SHEEP,          TileTypes.WOOD,            TileTypes.WHEAT,          TileTypes.WHEAT,          TileTypes.SEA            },
                    {TileTypes.PORT_SHEEP_2TO1, TileTypes.WHEAT,           TileTypes.WOOD,           TileTypes.BRICK,           TileTypes.SHEEP,          TileTypes.WOOD,            TileTypes.SHEEP,          TileTypes.DESERT,         TileTypes.PORT_ANY_3TO1},
                    {TileTypes.SEA,             TileTypes.SEA,             TileTypes.PORT_ANY_3TO1,  TileTypes.ROCK,            TileTypes.BRICK,          TileTypes.BRICK,           TileTypes.PORT_WHEAT_2TO1,TileTypes.SEA,            TileTypes.SEA            },
                    {TileTypes.SEA,             TileTypes.SEA,             TileTypes.SEA,            TileTypes.SEA,             TileTypes.PORT_SHEEP_2TO1,TileTypes.SEA,             TileTypes.SEA,            TileTypes.SEA,            TileTypes.SEA            },

                    {TileTypes.SEA,             TileTypes.SEA,             TileTypes.SEA,            TileTypes.SEA,             TileTypes.SEA,            TileTypes.SEA,          TileTypes.SEA,               TileTypes.SEA,            TileTypes.SEA            },
                };

                for (int y = 0; y < 7; y++)
                {
                    xPlotPos = hexScale / 2.0f;

                    for (int x = 0; x < 9; x++)
                    {
                        Tile t = new Tile((Object) this);

                        t.addPoint((int) (-1.0f * hexScale), (int) (0.0f * hexScale));
                        t.addPoint((int) (-0.5f * hexScale), (int) (1.0f * hexScale));
                        t.addPoint((int) (0.5f * hexScale),  (int) (1.0f * hexScale));
                        t.addPoint((int) (1.0f * hexScale),  (int) (0.0f * hexScale));
                        t.addPoint((int) (0.5f * hexScale),  (int) (-1.0f * hexScale));
                        t.addPoint((int) (-0.5f * hexScale), (int) (-1.0f * hexScale));

                        t.translate((int) (hexScale / 2.0f) + (int) xPlotPos,
                                    (int) (hexScale / 2.0f) + (int) yPlotPos);

                        xPlotPos += hexScale * 1.5f;

                        if (x % 2 == 0)
                        {
                            yPlotPos -= hexScale;
                        }
                        else
                        {
                            yPlotPos += hexScale;
                        }
                        tileList.add(t);

                        t.type = scene[y][x];

                        // Construct mappings and game rule/constuction objects
                        this.addUniqueBuildPoints(t);
                        this.addUniqueRoardPoints(t);

                        // Add the robber if this is the desert
                        if (t.type == TileTypes.DESERT)
                        {
                            t.hasRobber = true;
                        }
                    }

                    yPlotPos += (hexScale * 3);
                }
                
                // Process/replace with Variant tiles
                switch (gameVariant)
                {
                    case VOLCANO:
                        // swap desert to volcano tile
                        for (Tile t:tileList)
                        {
                            if (t.type == TileTypes.DESERT)
                                t.type = TileTypes.VAR_VOLCANO;
                        }
                        break;
                }
                    
                this.linkBuildPointsToRoads   ();
                this.randomiseCatanScene      (evenlyRandResTiles, evenlyRandPortTiles);
                this.randomiseEvenlyDiceRolls (boardType, gameVariant);
                this.linkBuildPointsToPorts   ();                
            }
        }
        
        lastPaintWidth = hexScaleWidth;
    }

    public void pause (int milliSeconds)
    {
        try { Thread.sleep(milliSeconds); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
    }
    
    public void paintImmediately()
    {        
        super.paintImmediately(0, 0, this.getWidth(), this.getHeight());
    }
     
    public void clrDblBuffCache ()
    {
        // Make a refresh of the background
        this.saveTileBG = null;
    }
            
    // Kept so existing callers stay valid; the flash no longer needs a captured
    // background image - it is drawn as an overlay inside the normal paint cycle.
    public void blinkBGInit ()
    {
    }

    // Flash the freshly changed object (settlement/city/road, or a robbed tile).
    //
    // Instead of drawing straight into getGraphics() off the paint cycle (which
    // left the board corrupted when the window was resized mid-animation), we
    // toggle a highlight overlay on the changed object and repaint just its area
    // synchronously with paintImmediately(). Every frame is a real paint at the
    // current geometry, so a resize during the flash repaints cleanly. Like the
    // dice-roll animation, this blocks the (single) game thread with short pauses.
    public void blinkBGObj (long time, CatanGraphBase obj, Rectangle robberErase)
    {
        if (this.gameWindow.gameRules.gameCompTesting != false)
            return;

        try
        {
            Rectangle objArea = null;

            // determine update area
            if (obj instanceof BuildPoint)
            {
                objArea = ((BuildPoint)obj).calcBuildSize();
            }
            else if (obj instanceof Road)
            {
                objArea = ((Road)obj).calcBuildSize();
            }
            else if (obj instanceof Tile)
            {
                objArea = ((Tile)obj).getBounds();
            }
            else
                return;

            // Clear any stale drawing (e.g. the robber's previous tile) once.
            if (robberErase != null)
            {
                this.paintImmediately(robberErase);
            }

            this.blinkObj = obj;

            long currentTime = System.currentTimeMillis();
            long endTime     = currentTime + time;

            while (currentTime < endTime)
            {
                this.blinkOn = true;
                this.paintImmediately(objArea);
                pause (25);
                this.blinkOn = false;
                this.paintImmediately(objArea);
                pause (25);
                currentTime = System.currentTimeMillis();
            }
        } catch (Exception e) { e.printStackTrace(); }
        finally
        {
            this.blinkObj = null;
            this.blinkOn  = false;
            this.repaint();
        }
    }

    public void blinkBG (long time)
    {
        if (this.gameWindow.gameRules.gameCompTesting != false)
            return;

        this.repaint();
    }
           
    public BufferedImage splodeInit (BuildPoint bp, Rectangle rtnLocation)
    {       
        try
        {
        Rectangle objArea = null;
        Rectangle drawAt  = null;

        // determine update area 
        objArea = bp.calcBuildSize();  
        drawAt  = new Rectangle (objArea);
        drawAt.setLocation(0, 0);               
        
        BufferedImage splodeImg = new BufferedImage (objArea.width,   objArea.height,   BufferedImage.TYPE_INT_ARGB);
 
        // Draw into our work buffer
        bp.drawAt(splodeImg.createGraphics(), drawAt);
        
        rtnLocation.setBounds(objArea.x, objArea.y, objArea.width, objArea.height);
        return splodeImg;        
        }catch (Exception e){ e.printStackTrace(); }        
        return null;
    }
    
    public void splodeBuilding (int life, Rectangle loc, BufferedImage splodeImg, ExplodeTypes ext)
    {                    
        try
        {
        BufferedImage bg        = new BufferedImage (this.getWidth(), this.getHeight(), BufferedImage.TYPE_INT_ARGB);
        BufferedImage db        = new BufferedImage (this.getWidth(), this.getHeight(), BufferedImage.TYPE_INT_ARGB);                
               
        // Draw current back ground
        this.paint(bg.createGraphics());
                
        ParticalCollection pc = new ParticalCollection();   
                                                                     
        pc.buildExplosionSplit(splodeImg, 
                               ext,
                               loc.x,                                                                                                                
                               loc.y, 
                               false,
                               1.5f,
                               life,
                               1);        
        int x = 0;
        Graphics2D g2   = (Graphics2D)this.getGraphics();
        Graphics2D g2db = (Graphics2D)db.getGraphics();
        long       maxTime = System.currentTimeMillis() + (life * 16);
        long       ts;
        long       te = maxTime;
        long       w;
        while ((pc.collection.size() > 0) && (te <= maxTime))
        {            
            ts = System.currentTimeMillis();
            g2db.drawImage(bg, 0, 0, null);
            pc.updateAll(g2db);            
            g2.drawImage(db, 0, 0, null);   
            
            // delay the next update....
            te = System.currentTimeMillis();
            w  = 16 - (te - ts);
            if (w > 0) pause ((int)w);
        }           
        
        g2.drawImage(db, 0, 0, null);  
        
        }catch (Exception e){ e.printStackTrace(); }
    }

    //***************************************************************************************
       
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,  RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.setRenderingHint(RenderingHints.KEY_RENDERING,     RenderingHints.VALUE_RENDER_QUALITY);
        
        try
        {       
            // If nothing to draw ... return 
            if (tileList.size() < 2) return;

            // Calculate ySize of the play area to center in screen.
            double diff = ((double) this.getWidth() / (double) hexScaleWidth) * 0.85; // 0.85 == magic number to make it scale correcly to fit every thing in screen, yeah its a hack!

            if (this.getWidth() > this.getHeight())
                diff = ((double) this.getHeight()  / (double)hexScaleWidth) * 0.85;

            Tile tYLen = tileList.get(tileList.size()-2);
            Tile tXLen = tileList.get(tileList.size()-1);

            tYLen.scale(diff, 0, 0);
            tXLen.scale(diff, 0, 0);

            int yLen    = (int) ((tYLen.getBounds2D()).getY() + (tYLen.getBounds2D()).getHeight());
            int xLen    = (int) ((tXLen.getBounds2D()).getX() + (tXLen.getBounds2D()).getWidth());
            int yCentre = (int) ((this.getHeight() - yLen) / 2);
            int xCentre = (int) ((this.getWidth()  - xLen) / 2);

            // ---- Re-scale output ----        
            boolean resized = false;
            if ((lastPaintWidth != this.getWidth()) || (lastPaintHeight != this.getHeight()))
            {
                resized = true;
                for (Tile t : tileList)
                {
                    t.scale(diff, xCentre, yCentre);
                }
                for (BuildPoint bp : buildList)
                {
                    bp.scale(diff, xCentre, yCentre);
                }
                for (Road r : roadList)
                {
                    r.scale(diff, xCentre, yCentre);
                }
                
                lastPaintWidth  = this.getWidth();
                lastPaintHeight = this.getHeight();
            }
            
            // -------------------------------------------------------

            // Create a new static bitmap of the tile background to 
            // speed up updates at the expense of memory.
            if ((resized != false) || (saveTileBG == null))            
            {
                saveTileBG = new BufferedImage (this.getWidth(), this.getHeight(), BufferedImage.TYPE_INT_ARGB);
                Graphics2D stbg_g2 = saveTileBG.createGraphics();
                
                // paint the background 
                if ((this.bgImage != null) && (detailLevelHigh != false))
                {
                    int h = this.getHeight();
                    int w = this.getWidth();
                    for (int y = 0; y < h; y += bgImage.getHeight())
                    {
                        for (int x = 0; x < w; x += bgImage.getWidth())
                        {
                            stbg_g2.drawImage(bgImage, x, y, this);
                        }
                    }
                }

                // ---- Draw Titles -----                       
                for (Tile t : tileList)
                    t.paint(stbg_g2, detailLevelHigh);
                
                // ---- Draw Sea Borders (fill in the cracks) -----       
                // Set the drawing line size 
                Tile tt = tileList.getLast();
                Rectangle2D rect = tt.getBounds2D();
                int width = (int) (rect.getWidth() / 30);
                g2.setStroke(new BasicStroke(width));

                for (Tile t : tileList)
                    t.drawHideBorder(stbg_g2, true, detailLevelHigh);
                
                // ---- Draw Land Borders (fill in the cracks) -----       
                for (Tile t : tileList)
                    t.drawHideBorder(stbg_g2, false, detailLevelHigh);
                
                for (Tile t : tileList)
                    t.drawPorts(stbg_g2, detailLevelHigh);                                                                                             
            }

            // -------------------------------------------------------
            
            // Dump the static background onto the display area.
            g2.drawImage(saveTileBG, 0, 0, null);
                        
            // ---- Draw Roads  -----    
            for (Road r : roadList)
                r.paint(g2);

            // ---- Draw Build Points  -----
            for (BuildPoint bp : buildList)
                bp.paint(g2);

            // Draw high-lighted objects
            if ((hlRender != false) && (hlLastSelObj != null))
            {
                if (hlLastSelObj instanceof BuildPoint)
                {
                    ((BuildPoint)hlLastSelObj).highLightSelectedDraw ((Graphics2D)g, Color.white);
                }
                else if (hlLastSelObj instanceof Road)
                {
                    ((Road)hlLastSelObj).highLightSelectedDraw ((Graphics2D)g, Color.white);
                }
                else if (hlLastSelObj instanceof Tile) // Move Robber ...
                {
                    ((Tile)hlLastSelObj).highLightSelectedDraw ((Graphics2D)g, Color.white);
                }
            }

            // Flash overlay for a freshly changed object (see blinkBGObj).
            if ((blinkOn != false) && (blinkObj != null))
            {
                if (blinkObj instanceof BuildPoint)
                {
                    ((BuildPoint)blinkObj).highLightSelectedDraw ((Graphics2D)g, Color.white);
                }
                else if (blinkObj instanceof Road)
                {
                    ((Road)blinkObj).highLightSelectedDraw ((Graphics2D)g, Color.white);
                }
                else if (blinkObj instanceof Tile)
                {
                    ((Tile)blinkObj).highLightSelectedDraw ((Graphics2D)g, Color.white);
                }
            }
        } catch (Exception e) { e.printStackTrace(); }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
