package Catan;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Point;
import javax.swing.JComponent;
import javax.swing.JPanel;

/**
 *
 * @author  Steven De Toni
 * 
 *  April 2008
 */
public class MessageJDialog extends javax.swing.JDialog
{
    boolean yesNo        = false;
    boolean userYesNoSel = false;

   
    /** Creates new form MessageJDialog */
    public MessageJDialog (java.awt.Frame parent, boolean modal, boolean yesNo)
    {
        super (parent, modal);
        initComponents ();
        
        this.yesNo = yesNo;
        if (yesNo != false)
        {
            yes.setVisible (true);
            no.setVisible (true);
            ok.setVisible(false);
        }
        else
        {
            yes.setVisible (false);
            no.setVisible  (false);
            ok.setVisible  (true);            
        }        
        
        this.setSize(this.getPreferredSize()); 
    
        centre (parent);
    }

    public void centre (Frame parent)
    {
        if (parent != null)
        {
            Point pp = parent.getLocationOnScreen();
            
            this.setLocation((pp.x + parent.getWidth()/2) - (this.getWidth()/2), 
                             (pp.y + parent.getHeight()/2) - (this.getHeight()/2));
        }
    }      

    public void centreToPanel (JComponent p)
    {
        if (p != null)
        {
            Point pp = p.getLocationOnScreen();
            
            this.setLocation((pp.x + p.getWidth()/2) - (this.getWidth()/2), 
                             (pp.y + p.getHeight()/2) - (this.getHeight()/2));
        }
    }  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borderPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        yes = new javax.swing.JButton();
        no = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        borderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        borderPanel.setMinimumSize(borderPanel.getPreferredSize());
        borderPanel.setName("Blah"); // NOI18N
        borderPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setMinimumSize(jScrollPane1.getPreferredSize());

        ok.setText("O.K");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel2.add(ok);

        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });
        jPanel2.add(yes);

        no.setText("No");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        jPanel2.add(no);

        borderPanel.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        msg.setBackground(getBackground());
        msg.setBorder(null);
        msg.setContentType("text/html");
        msg.setEditable(false);
        msg.setFont(new java.awt.Font("Tahoma", 1, 11));
        msg.setMinimumSize(msg.getPreferredSize());
        jScrollPane1.setViewportView(msg);

        borderPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, borderPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(borderPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-240)/2, (screenSize.height-148)/2, 240, 148);
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_okActionPerformed
    {//GEN-HEADEREND:event_okActionPerformed
        this.setVisible(false); 
    }//GEN-LAST:event_okActionPerformed

    private void yesActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_yesActionPerformed
    {//GEN-HEADEREND:event_yesActionPerformed
        userYesNoSel = true;
        this.setVisible(false); 
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_noActionPerformed
    {//GEN-HEADEREND:event_noActionPerformed
        userYesNoSel = false;
        this.setVisible(false); 
    }//GEN-LAST:event_noActionPerformed
        
    public void setText (String t, boolean centre)
    {
        Font  f = msg.getFont();
        Color c = borderPanel.getBackground();
        String txt = "<body bgcolor=\"rgb(235,233,237)>" +                
                     "<font size=\"2\" face=\""  + f.getName() + "\"><b>";
        
        if (centre != false)
            msg.setText(txt + "<center>" + t.replaceAll("\n", "<br>"));
        else
            msg.setText(txt + t.replaceAll("\n", "<br>"));
        this.setSize (borderPanel.getPreferredSize());
        
        centre ((Frame) this.getParent());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel borderPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane msg;
    private javax.swing.JButton no;
    private javax.swing.JButton ok;
    private javax.swing.JButton yes;
    // End of variables declaration//GEN-END:variables
    
}
