package Catan;

import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Point;
import java.util.LinkedList;
import javax.swing.JComponent;
import javax.swing.border.SoftBevelBorder;

/**
 *
 * @author  Steven De Toni
 * 
 *  April 2008
 */
public class RobOver7CardsJDialog extends javax.swing.JDialog
{
    class ResClickInfo
    {
        ResCardTypes type  = ResCardTypes.NULL;
        int          left  = 0, top    = 0;
        int          right = 0, bottom = 0;
        
        public boolean clicked (Point p)
        {
            if ((p.x>=left &&p.x<=right) &&
                (p.y>=top && p.y <= bottom))
            {
                return true;
            }               
            return false;
        }
    }
    // --------------------------------------------

    SoftBevelBorder           sbb          = new SoftBevelBorder(SoftBevelBorder.RAISED);
    LinkedList<ResClickInfo>  clickRegions = new LinkedList<ResClickInfo>();
    Player                    player       = null;
    int                       delCount     = 0;
    boolean                   completedOK  = false;
        
    /** Creates new form RobOver7CardsJDialog */
    public RobOver7CardsJDialog (java.awt.Frame parent, boolean modal)
    {
        super (parent, modal);
        initComponents (); 
        centre (parent);
    }
    
    public void centre (Frame parent)
    {
        if (parent != null)
        {
            Point pp = parent.getLocationOnScreen();
            
            this.setLocation((pp.x + parent.getWidth()/2) - (this.getWidth()/2), 
                             (pp.y + parent.getHeight()/2) - (this.getHeight()/2));
        }
    }   
    
    public void centreToPanel (JComponent p)
    {
        if (p != null)
        {
            Point pp = p.getLocationOnScreen();
            
            this.setLocation((pp.x + p.getWidth()/2) - (this.getWidth()/2), 
                             (pp.y + p.getHeight()/2) - (this.getHeight()/2));
        }
    }      
    
    public void assignPlayer (Player player)
    {
        this.player = player;
        
        if (player.resCards.size() > 7)
            delCount = player.resCards.size() / 2;
        else
            delCount = 0;
        
        repaint();
    }
    
    public void renderResCards (Graphics g)
    {       
        int xOffset = 10;
        int yOffset = actionLabel.getHeight() + 10;
        int count   = 0;
        int maxY    = yOffset;
        ResCardTypes dispOrder[] = {ResCardTypes.SHEEP, ResCardTypes.WHEAT, ResCardTypes.BRICK, ResCardTypes.WOOD, ResCardTypes.ROCK};

        clickRegions.clear();
        for (int idx = 0; idx < dispOrder.length; idx++)
        {
            int yCnt = 0;                                           
            ResourceCard lastRC = null;
            for (ResourceCard rc:player.resCards)
            {
                if (rc.type == dispOrder[idx])
                {
                    if (g != null)
                        rc.drawAt(null, g, xOffset, yOffset + (yCnt * (rc.getHeight()/2)), false, player.gameRules.gameTurnNo);
                    lastRC = rc;
                    yCnt++;
                }
            }                        
            if ((yCnt > 0) && (lastRC != null))
            {
                // Add/Create a mouse click region to test mouse clicks on particular resource cards
                ResClickInfo rci = new ResClickInfo();
                rci.left   = xOffset;
                rci.top    = yOffset;                
                rci.right  = xOffset + lastRC.getWidth();
                rci.bottom = yOffset + ((yCnt+1) * (lastRC.getHeight()/2));
                rci.type   = dispOrder[idx];
                clickRegions.add (rci);               
                
                xOffset = xOffset + (lastRC.getWidth() + 5);
                if (maxY < rci.bottom + 10)
                    maxY = rci.bottom + 10;
            }                        
        }        
        
        this.setSize(this.getWidth(), maxY);

        setActionLabel (player.name + " delete half (" + delCount + ") of your resource cards\nbecause 7 was rolled.");
    }       
    
    public void setActionLabel (String s)
    {
        actionLabel.setText ("<b><center>" + s.replaceAll("\n", "<br>") + "</center></b>");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        actionLabel = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                formMouseClicked(evt);
            }
        });

        actionLabel.setBackground(getBackground());
        actionLabel.setBorder(null);
        actionLabel.setContentType("text/html");
        actionLabel.setEditable(false);
        actionLabel.setFont(getFont());
        actionLabel.setText("<center>HTML Line 1<br>HTML Line 2</center>");
        jScrollPane1.setViewportView(actionLabel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-314)/2, (screenSize.height-185)/2, 314, 185);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked (java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseClicked
    {//GEN-HEADEREND:event_formMouseClicked
        if (player == null)
            return;
               
        for (ResClickInfo rci:clickRegions)        
        {           
            if (rci.clicked(evt.getPoint()) != false)
            {
                //remove selected type resource from the player
                for (ResourceCard rc:player.resCards)
                {
                    if (rc.type == rci.type)
                    {   
                        if (delCount > 0)
                        {
                            delCount--;
                            player.resCards.remove(rc);                                                                          
                        }
                        
                        if (delCount <= 0)
                        {
                            completedOK = true;
                            this.setVisible(false); 
                        }
                        
                        this.repaint();
                        return;
                    }
                }

            }                        
        }
        
        if (delCount <= 0)
        {
            completedOK = true;
            this.setVisible(false); 
        }
        
        this.repaint();
    }//GEN-LAST:event_formMouseClicked

    @Override
    public void paint (Graphics g)
    {
        g.clearRect(0, 0, this.getWidth(), this.getHeight());
        
        super.paint(g);
        
        sbb.paintBorder(this, g, 0, 0, this.getWidth(), this.getHeight());
        
        if (player != null)
        {
            renderResCards (g);
        }        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane actionLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
