package Catan;

import java.awt.Graphics;
import java.awt.Point;
import java.util.LinkedList;

/**
 *
 * @author  Steven De Toni
 * 
 *  April 2008
 */

public class StealCardJPanel extends javax.swing.JPanel
{  
    public LinkedList              clickRegions = new LinkedList();   
    public Player                  player       = null;
    public Player                  robberPlayer = null;
    public StealPlyrResCardJDialog ownerNotify  = null;
    
    /** Creates new form StealCardJPanel */
    public StealCardJPanel (Player player, Player robberPlayer, StealPlyrResCardJDialog ownerNotify)
    {
        this.player       = player;
        this.robberPlayer = robberPlayer;
        this.ownerNotify  = ownerNotify;
        initComponents ();
    }
    
    public boolean hasCards ()
    {
        if (player.resCards.size() > 0)
            return true;
        
        return false;
    }
        
    public void renderResCards (Graphics g)
    {   
        clickRegions.clear();
        int x     = 10;
        int y     = 20;               
        int count = 0;            
        int inset = this.getInsets().right;
        for (ResourceCard rc:player.resCards)
        {            
            if ((x+rc.getWidth()) >= this.getWidth()-((10*2)+inset))
            {
                x = 10;
                y = y + rc.getHeight() + 10;
            }
            else if (count > 0)
            {
                x = x + (rc.getWidth()/2);  // over lap cards 
            }

            rc.drawAt(null, g, x, y, true, player.gameRules.gameTurnNo); // display as a hidden card
            count++;
            
            // Add/Create a mouse click region to test mouse clicks on particular resource cards
            rc.setLocation(x, y);
        }   
        
        if (player.type == PlayerTypes.COMPUTER)
            vpInfo.setText ("Known Victory Points: " + player.vicPntsPublic);
        else
            vpInfo.setText ("Total Victory Points: " + player.vicPntsTotal);
    }

    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        renderResCards (g);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vpInfo = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        vpInfo.setText(" ");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(vpInfo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(vpInfo)
                .addContainerGap(226, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked (java.awt.event.MouseEvent evt)//GEN-FIRST:event_formMouseClicked
    {//GEN-HEADEREND:event_formMouseClicked
     
        // Did the click land on this victim's (face-down) cards at all?
        Object objs[] = player.resCards.toArray();
        Point  p      = evt.getPoint();
        boolean onACard = false;
        for (int idx = objs.length-1; idx >= 0; idx--)
        {
            if (((ResourceCard)objs[idx]).clicked(p) != false)
            {
                onACard = true;
                break;
            }
        }
        if (onACard == false)
            return;    // missed the cards - wait for a real selection

        // The cards are hidden, so the robber cannot legitimately choose which
        // one to take. Clicking anywhere on this victim's cards steals a
        // uniformly random one - the same logic the computer uses - instead of
        // the top-most (last-added) card the overlapped hit-test used to return.
        ResourceCard rc = robberPlayer.stealRandomCard(player);
        if (rc != null)
        {
            player.gameRules.setLog (robberPlayer.name + " stole " + rc.type.toString() + " from " + player.name);
        }

        ownerNotify.completedOK = true;
        ownerNotify.dispose();

    }//GEN-LAST:event_formMouseClicked
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel vpInfo;
    // End of variables declaration//GEN-END:variables
    
}
