/*
 * GameEndPntGraphJDialog.java
 *
 * Created on 4 May 2008, 21:16
 */
package Catan;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.Stroke;
import java.util.LinkedList;

/**
 *
 * @author  Steven De Toni
 * 
 *  May 2008
 */ 
public class GameEndPntGraphJDialog extends javax.swing.JDialog
{
    public LinkedList<GameRules.StatsRound> gameStats = null;
        
    /** Creates new form GameEndPntGraphJDialog */
    public GameEndPntGraphJDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();             
    } 
    
    public void assignGameStats (LinkedList<GameRules.StatsRound> gameStats)
    {
        this.gameStats = gameStats;
    }

    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
                
        // Build a graph        
        Graphics2D g2 = (Graphics2D)g;        
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);      
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);      
        g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);                     
                
        int    w = this.getWidth();
        int    h = this.getHeight();
        Insets i = this.getInsets();
        int    xT = i.left+10;
        int    yT = i.top+10;
        int    xB = w-i.right-10;
        int    yB = h-i.bottom-10;
         
        g2.setColor(Color.black);        
        g2.drawLine(xT, yT, xT, yB);
        g2.drawLine(xT, yB, xB, yB);  
        

        // Determine max end game point to plot graph
        int maxPoints = 1;        
        GameRules.StatsRound tnts = gameStats.getLast();               
        for (GameRules.StatsPlyr p:tnts.plyrs)            
        {   
            if (maxPoints < p.tpnts)
                maxPoints = p.tpnts;
        }
        
        // Draw graph Marks
        float yInc = ((float)(yB - yT) / (float)maxPoints);
        
        Stroke saveStroke = (Stroke) g2.getStroke();
        float [] dash = {3.0F, 2.0F, 3.0F, 2.0F };                                         

        g2.setStroke(new BasicStroke (1, BasicStroke.CAP_ROUND, BasicStroke.JOIN_MITER, 10.0F, dash, 0.F));
        g2.setColor(Color.lightGray);        
        
    
        for (int inc = 0; inc < maxPoints; inc++)
        {
            g2.drawLine (xT, yT + (int)((float)inc * yInc), 
                         xB, yT + (int)((float)inc * yInc));             
        }
               
        if (gameStats == null) return;
        
        // Draw vertical grid        
        float xInc = ((float)(xB - xT) / (float)gameStats.size());        
        for (int inc = 1; inc <= gameStats.size(); inc++)
        {
            g2.drawLine (xT + (int)((float)inc * xInc), yT,
                         xT + (int)((float)inc * xInc), yB);                         
        }
        
        g2.setStroke(saveStroke);
        
        // Draw points Graph        
        if (gameStats.size() <= 0) return;
        
        
        g2.setStroke(new BasicStroke (3, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND, 10.0F, null, 0.F));
        
        GameRules.StatsRound p = gameStats.getFirst();
        for (int pIdx = 0; pIdx < p.plyrs.size(); pIdx++)
        {
            float xLast = xT;
            float yLast = yB;
            int   step = 0;
            
            for (GameRules.StatsRound pi:gameStats)
            {                                    
                GameRules.StatsPlyr pr = pi.plyrs.get(pIdx);
                
                g2.setColor(pr.col);
                g2.drawLine ((int)xLast, (int)yLast, 
                             (int)(xLast + xInc ), (int) ((yB - yInc * (float)pr.tpnts) - (float)(pIdx)));
                
                yLast = yB  - (yInc * (float)pr.tpnts) - (float)(pIdx);
                xLast += xInc;
            }            
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Player Points Over Game Rounds");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 311, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 291, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-319)/2, (screenSize.height-320)/2, 319, 320);
    }// </editor-fold>//GEN-END:initComponents

private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
    repaint();
}//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                GameEndPntGraphJDialog dialog = new GameEndPntGraphJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {

                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
