package Catan;

import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;

/**
 *
 * @author  Steven De Toni
 * 
 *  April 2008
 */
public class GameEndJDialog extends javax.swing.JDialog {

    boolean startNewGame = false;
    Player  plyr         = null;
    
    /** Creates new form GameEndJDialog */
    public GameEndJDialog(java.awt.Frame parent, boolean modal, Player plyrWon) 
    {
        super(parent, modal);
        initComponents();                
        plyr = plyrWon;
        this.setTitle(plyr.name + " has Won");
        
        centre (parent);
    }

    public void centre (Frame parent)
    {
        if (parent != null)
        {
            Point pp = parent.getLocationOnScreen();
            
            this.setLocation((pp.x + parent.getWidth()/2) - (this.getWidth()/2), 
                             (pp.y + parent.getHeight()/2) - (this.getHeight()/2));
        }
    }  
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        viewGrpahButton = new javax.swing.JButton();
        okGameButton = new javax.swing.JButton();
        newGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setName("EndGame"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wins!");

        viewGrpahButton.setText("View Graph");
        viewGrpahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGrpahButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewGrpahButton);

        okGameButton.setText("View Cards");
        okGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okGameButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okGameButton);

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });
        jPanel1.add(newGameButton);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 221, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-232)/2, (screenSize.height-359)/2, 232, 359);
    }// </editor-fold>//GEN-END:initComponents

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    startNewGame = false;
}//GEN-LAST:event_formWindowClosing

private void okGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okGameButtonActionPerformed
    startNewGame = false;
    this.dispose();
}//GEN-LAST:event_okGameButtonActionPerformed

private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
    startNewGame = true;
    this.dispose();
}//GEN-LAST:event_newGameButtonActionPerformed

private void viewGrpahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGrpahButtonActionPerformed
    GameEndPntGraphJDialog g = new GameEndPntGraphJDialog (plyr.gameRules.gameWindow, true);
    
    g.assignGameStats(plyr.gameRules.plyrStatsRoundList);
    g.setVisible(true);
}//GEN-LAST:event_viewGrpahButtonActionPerformed

    @Override
    public void paint (Graphics g)
    {
        super.paint(g);
        
        if (plyr != null)
        {
            Graphics2D g2 = (Graphics2D)g;        
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);      
            g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);      
            g2.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);                     
             
            // Paint this traders icon        
            Insets inset = this.getInsets();
            BufferedImage bi        = plyr.getPlayerImage();
            int           newHeight = 180;
            float         reduce    = (float)newHeight / (float)bi.getHeight();
            int           newWidth  = (int)((float)bi.getWidth()*reduce);
            int           xPos      = (this.getWidth()/2) - (newWidth/2);           
                
            g2.drawImage(bi, xPos, inset.top + 10, newWidth, newHeight, null);                            
        }        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton okGameButton;
    private javax.swing.JButton viewGrpahButton;
    // End of variables declaration//GEN-END:variables
}
